### ISSUE TITLE
lastUpdated field gets updated on each run

### ISSUE THREAD

**Issue by gabesawhney** [spiderbites/to-planning-applications#2]
It should only update when there's new data. Maybe this needs a schema change, or maybe we can't use REPLACE INTO?

**Comment by spiderbites** [comment]
REPLACE INTO it turns out actually deletes the row and then re-inserts it, so there is really no updating possible with that statement.  i've replaced it with the this mysql statement:
INSERT INTO .... ON DUPLICATE KEY UDPATE ...
